### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by yantakus** [evcohen/react-proptype-conditional-require#5]
Examples form the README are incorrect. This line to be exact:

```
import isRequiredIf from 'react-proptype-conditional-require';
```

There's no `index.js` file, so we can't import like this.

**Comment by beefancohen** [comment]
ah sorry about that, messed up the build. fixing now.

**Comment by beefancohen** [comment]
Fixed in [v1.0.4](https://github.com/evcohen/react-proptype-conditional-require/releases/tag/1.0.4) thanks for reporting 😄

**Comment by yantakus** [comment]
Thanks. But it's quite useless unless you publish it on npm :)

**Comment by beefancohen** [comment]
haha it just finished
